image: node:14

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - |
    echo "Node.js version: $(node --version)"
    echo "NPM version: $(npm --version)"
    echo "Current working directory: $(pwd)"
    npm cache clean --force
    rm -rf node_modules package-lock.json
    npm install
    npm list

test_job:
  stage: test
  script:
    - npm test
  only:
    - main
    - merge_requests