image: python:3.9

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip
    - node_modules/
    - machineLearning/venv/

before_script:
  - |
    if [[ "$(uname)" == "Darwin" ]]; then
      # Preparing for Homebrew installation on macOS
      echo "Installing Node.js using Homebrew..."
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      echo 'export PATH="/usr/local/bin:$PATH"' >> $BASH_ENV
      source $BASH_ENV
      brew install node@16
      brew link node@16 --force
    else
      # Installing Node.js on Linux
      curl -sL https://deb.nodesource.com/setup_16.x | bash -
      apt-get install -y nodejs
    fi
    echo "Node.js version: $(node --version)"
    echo "NPM version: $(npm --version)"

    # Install Python environment and packages
    echo "Python version: $(python --version)"
    echo "PIP version: $(pip --version)"
    python -m venv machineLearning/venv
    source machineLearning/venv/bin/activate
    pip install --upgrade pip
    pip install numpy pandas scikit-learn joblib
    echo "Dependencies installed."

    # Prepare Node.js environment
    npm cache clean --force
    rm -rf node_modules package-lock.json
    npm install
    npm list

test_node:
  stage: test
  script:
    - npm test
  only:
    - main
    - merge_requests

test_python:
  stage: test
  script:
    - source machineLearning/venv/bin/activate
    - python machineLearning/testModel.py
  only:
    - main
    - merge_requests