image: python:3.9

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip
    - node_modules/
    - machineLearning/venv/

before_script:
  - |
    # Check the OS and install Node.js
    if [[ "$(uname)" == "Darwin" ]]; then
      # Installing Node.js on macOS using Homebrew
      echo "Installing Node.js using Homebrew..."
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
      brew install node@16
      brew link node@16 --force
    else
      # Installing Node.js on Linux
      echo "Installing Node.js using NodeSource for Linux..."
      curl -sL https://deb.nodesource.com/setup_16.x | bash -
      sudo apt-get install -y nodejs
    fi
    echo "Node.js version: $(node --version)"
    echo "NPM version: $(npm --version)"

    # Install Python environment and packages
    echo "Python version: $(python --version)"
    echo "PIP version: $(pip --version)"
    python -m venv machineLearning/venv
    source machineLearning/venv/bin/activate
    pip install --upgrade pip
    pip install numpy pandas scikit-learn joblib
    # Add any other dependencies you might need
    echo "Dependencies installed."

    # Prepare Node.js environment
    npm cache clean --force
    rm -rf node_modules package-lock.json
    npm install
    npm list

test_node:
  stage: test
  script:
    - npm test
  only:
    - main
    - merge_requests

test_python:
  stage: test
  script:
    - source machineLearning/venv/bin/activate
    - python machineLearning/testModel.py
  only:
    - main
    - merge_requests
